// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToDocument(arg1, arg2) {
  return window['go']['main']['App']['AddTagToDocument'](arg1, arg2);
}

export function AddTagToFilePath(arg1, arg2) {
  return window['go']['main']['App']['AddTagToFilePath'](arg1, arg2);
}

export function BatchAddTag(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTag'](arg1, arg2);
}

export function BatchRemoveTagFromDocuments(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromDocuments'](arg1, arg2);
}

export function CloseTagPicker() {
  return window['go']['main']['App']['CloseTagPicker']();
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportDatabase() {
  return window['go']['main']['App']['ExportDatabase']();
}

export function GetAppMode() {
  return window['go']['main']['App']['GetAppMode']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocumentCount() {
  return window['go']['main']['App']['GetDocumentCount']();
}

export function GetDocumentGraph() {
  return window['go']['main']['App']['GetDocumentGraph']();
}

export function GetDocumentTagsByPath(arg1) {
  return window['go']['main']['App']['GetDocumentTagsByPath'](arg1);
}

export function GetFileTypeCounts() {
  return window['go']['main']['App']['GetFileTypeCounts']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSupportedTypes() {
  return window['go']['main']['App']['GetSupportedTypes']();
}

export function GetTagGraph() {
  return window['go']['main']['App']['GetTagGraph']();
}

export function GetUntaggedCount(arg1) {
  return window['go']['main']['App']['GetUntaggedCount'](arg1);
}

export function ImportDatabase() {
  return window['go']['main']['App']['ImportDatabase']();
}

export function ListDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListDocuments'](arg1, arg2, arg3, arg4);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function RemoveDocument(arg1) {
  return window['go']['main']['App']['RemoveDocument'](arg1);
}

export function RemoveDocuments(arg1) {
  return window['go']['main']['App']['RemoveDocuments'](arg1);
}

export function RemoveTagFromDocument(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromDocument'](arg1, arg2);
}

export function RemoveTagFromFilePath(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromFilePath'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1, arg2) {
  return window['go']['main']['App']['ScanFolder'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetTagPickerMode(arg1) {
  return window['go']['main']['App']['SetTagPickerMode'](arg1);
}
