// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function AddTagToDocument(arg1:number,arg2:string):Promise<void>;

export function AddTagToFilePath(arg1:string,arg2:string):Promise<void>;

export function BatchAddTag(arg1:Array<number>,arg2:string):Promise<number>;

export function BatchRemoveTagFromDocuments(arg1:Array<number>,arg2:number):Promise<number>;

export function CloseTagPicker():Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExportDatabase():Promise<string>;

export function GetAppMode():Promise<Record<string, any>>;

export function GetDocument(arg1:number):Promise<database.DocumentDetail>;

export function GetDocumentCount():Promise<number>;

export function GetDocumentGraph():Promise<database.GraphData>;

export function GetDocumentTagsByPath(arg1:string):Promise<Array<database.Tag>>;

export function GetFileTypeCounts():Promise<Record<string, number>>;

export function GetSettings():Promise<main.Settings>;

export function GetSupportedTypes():Promise<Array<string>>;

export function GetTagGraph():Promise<database.GraphData>;

export function GetUntaggedCount(arg1:Array<string>):Promise<number>;

export function ImportDatabase():Promise<boolean>;

export function ListDocuments(arg1:Array<number>,arg2:string,arg3:boolean,arg4:Array<string>):Promise<Array<database.Document>>;

export function ListTags():Promise<Array<database.TagWithCount>>;

export function OpenFile(arg1:number):Promise<void>;

export function OpenFileLocation(arg1:number):Promise<void>;

export function RemoveDocument(arg1:number):Promise<void>;

export function RemoveDocuments(arg1:Array<number>):Promise<number>;

export function RemoveTagFromDocument(arg1:number,arg2:number):Promise<void>;

export function RemoveTagFromFilePath(arg1:string,arg2:number):Promise<void>;

export function RenameTag(arg1:number,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ScanFolder(arg1:string,arg2:Array<string>):Promise<main.ScanFolderResult>;

export function SelectFolder():Promise<string>;

export function SetTagPickerMode(arg1:string):Promise<void>;
